version: "3.9"
    
services:
  db:
    image: mysql:8.0
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    restart: always  
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD   
    
  flask_api:
    depends_on:
      - db
    image: nikolasht1/flaskapi:latest
    ports:
      - 5000:5000
    env_file: .env  
    restart: always
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOSTNAME=$DB_HOSTNAME
      - DB_NAME=$DB_NAME